version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.app
      FLASK_ENV: development
      DATABASE_URL: sqlite:////tmp/test.db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000

  tests:
    build: .
    command: python -m unittest discover -s tests
    environment:
      FLASK_APP: app.app
      FLASK_ENV: testing
      DATABASE_URL: "sqlite:///:memory:"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - app
